version: "3.8"

services:
  bookstore_app:
    build: .
    container_name: bookstore_app
    restart: always
    environment:
      PYTHONPATH: /app
      DJANGO_SETTINGS_MODULE: book_store.settings
      ADMIN_USERNAME: "admin"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"
      DATABASE_URL: ${DATABASE_URL}  # Use Railway's injected DB URL
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python scripts/create_admin.py &&
      python manage.py loaddata books/fixtures/data.json || true &&
      gunicorn book_store.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
